# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20160129_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passw_hash',
            new_name='passw',
        ),
    ]
